include: package:lints/recommended.yaml

analyzer:
  exclude: [build/**]
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - cancel_subscriptions
    - always_declare_return_types
    - avoid_init_to_null
    - valid_regexps
    - avoid_dynamic_calls
    - avoid_print
    - avoid_empty_else
    - unnecessary_getters_setters
    - always_use_package_imports
    - enable_null_safety
    - unsafe_html